version: "3"
services:
    riot-php:
        image: "pauulog/php-docker-dev:latest"
        container_name: "riot-php"
        links:
          - "riot-mariadb:mariadb.host"
        volumes:
            - "./:/riot-backend:rw"
        working_dir: /riot-backend
        restart: always
    riot-nginx:
        image: "nginx:1-alpine"
        container_name: "riot-nginx"
        links:
          - "riot-php:riot-php.host"
        ports:
          - 8080:80
        volumes:
            - "./:/riot-backend:rw"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:r"
        working_dir: /riot-backend
        restart: always
    riot-mariadb:
        image: "mariadb:10.6"
        container_name: "riot-mariadb"
        volumes:
            - "._mysql_data_dir/:/var/lib/mysql:rw"
        ports:
          - 3307:3306
        environment:
          - MARIADB_USER
          - MARIADB_PASSWORD
          - MARIADB_DATABASE
          - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
        restart: always